/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_CONSTANTS_H
#define server_CONSTANTS_H

#include "server_types.h"

namespace services {

class serverConstants {
 public:
  serverConstants();

};

extern const serverConstants g_server_constants;

} // namespace

#endif
